export const mockEvents = [
  {
    id: '1',
    title: 'Web3 Developer Conference 2024',
    description: 'Join the biggest Web3 developer conference featuring talks from industry leaders, hands-on workshops, and networking opportunities.',
    date: '2024-02-15T10:00:00Z',
    location: 'San Francisco, CA',
    imageUrl: 'https://images.pexels.com/photos/2608517/pexels-photo-2608517.jpeg?auto=compress&cs=tinysrgb&w=800',
    nftName: 'Web3 Dev Conf 2024',
    nftSymbol: 'W3DC24',
    registrations: 245,
    maxAttendees: 500,
    creatorId: 'user1',
  },
  {
    id: '2',
    title: 'DeFi Summit: Future of Finance',
    description: 'Explore the latest trends in decentralized finance, from yield farming to NFT lending protocols.',
    date: '2024-03-20T14:00:00Z',
    location: 'New York, NY',
    imageUrl: 'https://images.pexels.com/photos/8369648/pexels-photo-8369648.jpeg?auto=compress&cs=tinysrgb&w=800',
    nftName: 'DeFi Summit 2024',
    nftSymbol: 'DEFI24',
    registrations: 189,
    maxAttendees: 300,
    creatorId: 'user2',
  },
  {
    id: '3',
    title: 'NFT Art Exhibition Opening',
    description: 'An exclusive exhibition showcasing the finest digital art from emerging and established NFT artists.',
    date: '2024-01-10T18:00:00Z',
    location: 'Los Angeles, CA',
    imageUrl: 'https://images.pexels.com/photos/1839919/pexels-photo-1839919.jpeg?auto=compress&cs=tinysrgb&w=800',
    nftName: 'NFT Art Expo 2024',
    nftSymbol: 'ARTE24',
    registrations: 156,
    maxAttendees: 200,
    creatorId: 'user1',
  },
  {
    id: '4',
    title: 'Blockchain Gaming Workshop',
    description: 'Learn how to build play-to-earn games using blockchain technology and smart contracts.',
    date: '2024-04-05T13:00:00Z',
    location: 'Austin, TX',
    imageUrl: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=800',
    nftName: 'Game Dev Workshop 2024',
    nftSymbol: 'GAME24',
    registrations: 78,
    maxAttendees: 100,
    creatorId: 'user3',
  },
  {
    id: '5',
    title: 'Metaverse Real Estate Expo',
    description: 'Discover opportunities in virtual real estate across different metaverse platforms.',
    date: '2024-05-12T11:00:00Z',
    location: 'Miami, FL',
    imageUrl: 'https://images.pexels.com/photos/8566473/pexels-photo-8566473.jpeg?auto=compress&cs=tinysrgb&w=800',
    nftName: 'Metaverse Expo 2024',
    nftSymbol: 'META24',
    registrations: 234,
    maxAttendees: 400,
    creatorId: 'user2',
  },
  {
    id: '6',
    title: 'DAO Governance Workshop',
    description: 'Learn about decentralized autonomous organizations and how to participate in DAO governance.',
    date: '2024-06-18T15:00:00Z',
    location: 'Chicago, IL',
    imageUrl: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800',
    nftName: 'DAO Workshop 2024',
    nftSymbol: 'DAO24',
    registrations: 92,
    maxAttendees: 150,
    creatorId: 'user3',
  },
];

export const mockUserEvents = [
  {
    id: '1',
    title: 'Web3 Developer Conference 2024',
    description: 'Join the biggest Web3 developer conference featuring talks from industry leaders, hands-on workshops, and networking opportunities.',
    date: '2024-02-15T10:00:00Z',
    location: 'San Francisco, CA',
    imageUrl: 'https://images.pexels.com/photos/2608517/pexels-photo-2608517.jpeg?auto=compress&cs=tinysrgb&w=800',
    nftName: 'Web3 Dev Conf 2024',
    nftSymbol: 'W3DC24',
    registrations: 245,
    maxAttendees: 500,
    creatorId: 'user1',
  },
  {
    id: '3',
    title: 'NFT Art Exhibition Opening',
    description: 'An exclusive exhibition showcasing the finest digital art from emerging and established NFT artists.',
    date: '2024-01-10T18:00:00Z',
    location: 'Los Angeles, CA',
    imageUrl: 'https://images.pexels.com/photos/1839919/pexels-photo-1839919.jpeg?auto=compress&cs=tinysrgb&w=800',
    nftName: 'NFT Art Expo 2024',
    nftSymbol: 'ARTE24',
    registrations: 156,
    maxAttendees: 200,
    creatorId: 'user1',
  },
];

export const mockNFTs = [
  {
    id: '1',
    eventId: '1',
    name: 'Web3 Dev Conf 2024',
    description: 'Proof of attendance for Web3 Developer Conference 2024',
    imageUrl: 'https://images.pexels.com/photos/2608517/pexels-photo-2608517.jpeg?auto=compress&cs=tinysrgb&w=400',
    mintAddress: '0x1234...5678',
    attendedAt: '2024-02-15T10:00:00Z',
  },
  {
    id: '2',
    eventId: '3',
    name: 'NFT Art Expo 2024',
    description: 'Proof of attendance for NFT Art Exhibition Opening',
    imageUrl: 'https://images.pexels.com/photos/1839919/pexels-photo-1839919.jpeg?auto=compress&cs=tinysrgb&w=400',
    mintAddress: '0x5678...9abc',
    attendedAt: '2024-01-10T18:00:00Z',
  },
];